//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("852")]
        public int MainFormSplitterDistanceAllRecipients {
            get {
                return ((int)(this["MainFormSplitterDistanceAllRecipients"]));
            }
            set {
                this["MainFormSplitterDistanceAllRecipients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182")]
        public int MainFormSplitterDistanceTweetsReplies {
            get {
                return ((int)(this["MainFormSplitterDistanceTweetsReplies"]));
            }
            set {
                this["MainFormSplitterDistanceTweetsReplies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("370")]
        public int MainFormSplitterDistanceRTs {
            get {
                return ((int)(this["MainFormSplitterDistanceRTs"]));
            }
            set {
                this["MainFormSplitterDistanceRTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainFormEditSearchResultsShowInForm {
            get {
                return ((bool)(this["MainFormEditSearchResultsShowInForm"]));
            }
            set {
                this["MainFormEditSearchResultsShowInForm"] = value;
            }
        }
    }
}
