start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\App.config"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Data\DataSet.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Data\DataSet.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Data\DataSet.xsd"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Properties\AssemblyInfo.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Properties\DataSources\Ordisoftware.TweetsInspector.Properties.Settings.datasource"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Properties\Resources.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Properties\Settings.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Properties\Settings.settings"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Controls\TweetsListControl.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Controls\TweetsListControl.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Controls\TweetsListsControl.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Controls\TweetsListsControl.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.DB.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.LoadTweetsFromJS.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.Messages.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\MainForm.resx"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\WebBrowserForm.Designer.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Forms\WebBrowserForm.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Program\DataSet.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Source\Program\Program.cs"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Tweets Inspector (vs2017).csproj"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Project\Tweets Inspector (vs2017).sln"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\README.md"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\Setup\OrdisoftwareTweetsInspectorSetup.iss"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\System\ResetSettings.bat"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\System\Web Ordisoftware.com.url"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\System\Web Tweets Inspector.url"
start notepad "C:\Users\Olivier\Projects\Software\Public\Tweets Inspector\System\Web Twitter Manager.url"
